---
name: Sphinx build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build HTML
        run: make docs
      - uses: actions/upload-pages-artifact@v0.1.0
        with:
          name: docs/_build/html
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy docs
        uses: actions/deploy-pages@v1
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
